# Generated by Django 6.1.1 on 2026-10-02 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.PositiveIntegerField(help_text='Savol asl raqami (1 dan 16 gacha)', unique=True),
        ),
        migrations.CreateModel(
            name='GameCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.PositiveIntegerField(help_text='Doskadagi kartochka raqami (1 dan 16 gacha)')),
                ('is_opened', models.BooleanField(default=False, help_text='Kartochka ochilganmi?')),
                ('opened_at', models.DateTimeField(blank=True, help_text='Ochilgan vaqti', null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_cards', to='quiz.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "O'yin kartochkasi",
                'verbose_name_plural': "O'yin kartochkalari",
                'ordering': ['card_number'],
                'unique_together': {('user', 'card_number')},
            },
        ),
        migrations.DeleteModel(
            name='OpenedQuestion',
        ),
    ]
